
name: Integration

# on => on which event these jobs will be triggered
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # which particular machine the GitHub can use on server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4    # checkout to the current branch(i.e feature-branch) ==> by default it's on main branch
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # setup the node environment before doing anything else
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: "Installing Dependencies"
      run: npm i

    - name: "Build command"
      run: npm run build

  unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Installing Dependencies"
      run: npm i

    - name: "Running test cases"
      run: npm run test